// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsQxYjAfS6Zg_8fWgVaBgVHJdCLJvolfE',
    appId: '1:836312339884:web:488fcaea6bd5c7f5c95609',
    messagingSenderId: '836312339884',
    projectId: 'flashcards-2686d',
    authDomain: 'flashcards-2686d.firebaseapp.com',
    storageBucket: 'flashcards-2686d.firebasestorage.app',
    measurementId: 'G-99HJWY5H4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9laMxA9Cy9z7SqwITjVInKdd4CWIH4KM',
    appId: '1:836312339884:android:8b750a803e54726ec95609',
    messagingSenderId: '836312339884',
    projectId: 'flashcards-2686d',
    storageBucket: 'flashcards-2686d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADDiq7zMqHS51yoik93hn4aT9b5v2vUFY',
    appId: '1:836312339884:ios:d894bb20710bae12c95609',
    messagingSenderId: '836312339884',
    projectId: 'flashcards-2686d',
    storageBucket: 'flashcards-2686d.firebasestorage.app',
    iosBundleId: 'com.example.englishFlashcards',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADDiq7zMqHS51yoik93hn4aT9b5v2vUFY',
    appId: '1:836312339884:ios:d894bb20710bae12c95609',
    messagingSenderId: '836312339884',
    projectId: 'flashcards-2686d',
    storageBucket: 'flashcards-2686d.firebasestorage.app',
    iosBundleId: 'com.example.englishFlashcards',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsQxYjAfS6Zg_8fWgVaBgVHJdCLJvolfE',
    appId: '1:836312339884:web:08a066079a993b69c95609',
    messagingSenderId: '836312339884',
    projectId: 'flashcards-2686d',
    authDomain: 'flashcards-2686d.firebaseapp.com',
    storageBucket: 'flashcards-2686d.firebasestorage.app',
    measurementId: 'G-N7PWL0KD4Z',
  );
}
